#!/usr/bin/env bash
# CODES-DEVELOPER v12.4 — Codex Developer
# ctx: codexhaven
# add_path_header.sh - Add standard headers to generated files
# Usage: add_path_header.sh <filepath>

set -euo pipefail

FILEPATH="$1"
if [ -z "$FILEPATH" ]; then
  echo "Error: No file path provided"
  exit 1
fi

# Get file extension
EXT="${FILEPATH##*.}"
FILENAME=$(basename "$FILEPATH")
DIR=$(dirname "$FILEPATH")

# Ensure directory exists
mkdir -p "$DIR"

# Add appropriate headers based on file type
case "$EXT" in
  py)
    # Python file: add shebang and path header if not present
    if ! grep -q "^#!/usr/bin/env python3" "$FILEPATH" 2>/dev/null && ! grep -q "^#!" "$FILEPATH" 2>/dev/null; then
      # Insert shebang at the beginning
      sed -i '1i#!/usr/bin/env python3' "$FILEPATH"
    fi
    # Add path header for module resolution if not present
    if ! grep -q "sys.path.insert" "$FILEPATH" 2>/dev/null && ! grep -q "sys.path.append" "$FILEPATH" 2>/dev/null; then
      # Insert after shebang or at line 2 if no shebang, or at line 1 if neither
      if head -1 "$FILEPATH" | grep -q "^#!"; then
        sed -i '2iimport sys\nimport os\nsys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))' "$FILEPATH"
      else
        sed -i '1iimport sys\nimport os\nsys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))' "$FILEPATH"
      fi
    fi
    ;;
  sh)
    # Shell script: add shebang if not present
    if ! grep -q "^#!/" "$FILEPATH" 2>/dev/null; then
      sed -i '1i#!/usr/bin/env bash' "$FILEPATH"
    fi
    ;;
  js|ts)
    # JavaScript/TypeScript: add comment header if not present
    if ! grep -q "//" "$FILEPATH" 2>/dev/null | head -1; then
      # Not ideal, but we'll add a simple header comment
      sed -i '1i// Generated by codex-developer' "$FILEPATH"
    fi
    ;;
  *)
    # For other file types, do nothing special
    :
    ;;
esac

exit 0